FROM node:22.14-slim AS build

WORKDIR /workspace

COPY package.json package-lock.json* ./
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN npm install

COPY packages/shared packages/shared
COPY apps/web apps/web

RUN npm run build --workspace=@metergate/shared
RUN npm run build --workspace=@metergate/web


FROM node:22.14-slim

WORKDIR /workspace/apps/web

COPY --from=build /workspace/apps/web/.next .next
COPY --from=build /workspace/apps/web/public public
COPY --from=build /workspace/apps/web/package.json package.json
COPY --from=build /workspace/node_modules /workspace/node_modules
COPY --from=build /workspace/packages/shared /workspace/packages/shared

CMD ["npm", "run", "start"]
